### ISSUE TITLE
Include CRLF and NEL (U+0085) as line boundaries per UTS#18

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposal-regexp-set-notation#42]
This is a tracking issue for making the `v` flag affect the set of line boundaries that are considered. Specifically, per UTS#18 CRLF and NEL (U+0085) should be included. This affects `^` and `$` if the `m` flag is enabled, and `.` unless the `s` flag is enabled.

**Comment by markusicu** [comment]
This is no longer a goal for this proposal.
