### ISSUE TITLE
Expanded scope: further alignment with UTS#18

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposal-regexp-set-notation#43]
Tracking issue for further alignment with [UTS#18](https://unicode.org/reports/tr18/).

- Unicode-aware `\w`, `\d`, and `\b`: https://github.com/tc39/proposal-regexp-set-notation/issues/16
- Unicode-aware `\s`: https://github.com/tc39/proposal-regexp-set-notation/issues/37
- Include CRLF and NEL (U+0085) as line boundaries: https://github.com/tc39/proposal-regexp-set-notation/issues/42

[Spreadsheet comparing ECMAScript regex vs. Unicode regex](https://docs.google.com/spreadsheets/d/13_26QjFT6epzmNjiQGTSNsz-yyXvJqLtgU4mNHN0Dhs/edit)

**Comment by markusicu** [comment]
This is no longer a goal for this proposal.
