### ISSUE TITLE
maybe more spec edits

### ISSUE THREAD

**Issue by markusicu** [tc39/proposal-regexp-set-notation#57]
Review the spec once more and see if more edits are needed. For example, check on whether we need to consider "v" where "u" is used, or check whether we should use *EitherUnicode* instead of just *Unicode*. Recognize & carry where appropriate v, eu, etc.

It seems mostly fine, but look at the following.

- [x] 22.2.5.2.2 RegExpBuiltinExec ( R, S )
      8. If flags contains "u", let fullUnicode be true; else let fullUnicode be false.
- [x] 22.2.5.7 RegExp.prototype [ @@match ] ( string )
      b. Let fullUnicode be ! ToBoolean(? Get(rx, "unicode")).
- [x] 22.2.5.8 RegExp.prototype [ @@matchAll ] ( string )
      11. If flags contains "u", let fullUnicode be true.
- [x] 22.2.5.10 RegExp.prototype [ @@replace ] ( string, replaceValue )
      a. Let fullUnicode be ! ToBoolean(? Get(rx, "unicode")).
- [x] 22.2.5.13 RegExp.prototype [ @@split ] ( string, limit )
      6. If flags contains "u", let unicodeMatching be true.
- [x] B.1.2.7.1 CharacterRangeOrUnion ( A, B ) https://github.com/mathiasbynens/ecma262/pull/11
      1. If Unicode is false, then

(This issue replaces the old TODOs that I removed in https://github.com/tc39/ecma262/commit/973f91fea10d7aa7d31b818faba7bcc8d2773847)

**Comment by mathiasbynens** [comment]
Patch for the remaining items: https://github.com/mathiasbynens/ecma262/pull/13
